const dbTypes = {
    LOCATION_USER: 'LOCATION_USER',
    CITY_USER: 'CITY_USER',
    STATES_USER: 'STATES_USER',
    UNIT_USER: 'UNIT_USER',
    ZIP_CODE_USER: 'ZIP_CODE_USER',
    ABOUT_PROPERTY: 'ABOUT_PROPERTY',
    TYPE_PROPERTY: 'TYPE_PROPERTY',
    COUNT_UNIT: 'COUNT_UNIT',
    INVEST_VALUE: 'INVEST_VALUE',
    HOME_VALUE: 'HOME_VALUE',
    NEXT_CLICK: 'NEXT_CLICK',
    BACK_CLICK: 'BACK_CLICK'
};

export default dbTypes;
